tempo:
  enabled: true
  mode: "single"

  metricsGenerator:
    enabled: true

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces

  # service:
  #   type: NodePort
  #   nodePort: 32001
  # service:
  #   type: ClusterIP
  #   port: 3200
  #   tempoQuery:
  #     enabled: true

  auth_enabled: false