persistence:
  enabled: false

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline: 
 logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if "CrashLoopBackOff" in [message] {
          mutate { add_tag => "abhradip" }
        }
      }
    output {
      elasticsearch {
        hosts => "https://elasticsearch-master:9200"
        user => "elastic"
        password => "abhradip"
        ssl => true
        ssl_certificate_verification => false
        manage_template => false
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
      }
      if "abhradip" in [tags] {
        stdout { }

        email {
          to => "@gmail.com"
          username => "@gmail.com"
          from => "@gmail.com"
          password => ""
          subject => "Alert - CrashLoopBackOff detected"
          body => "Tags: %{tags}\nContent:\n%{message}"
          # template_file => "/tmp/email_template.mustache"
          address => "smtp.gmail.com"
          via => "smtp"
          use_tls => true
          authentication => "plain"
          port => 587
        }
      }
    }

service:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080